= COVID-19-Maßnahmengesetz
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:risVor2004: https://www.ris.bka.gv.at/Dokument.wxe?Abfrage=BgblPdf&Suchworte=1994_315_0&SkipToDocumentPage=true&Dokumentnummer=

[CAUTION]
.Haftungsausschluss
====
Diese Seite dient nur dem Zweck, die verschiedenen Novellen des
https://www.ris.bka.gv.at/eli/bgbl/I/2020/12[_COVID-19-Maßnahmengesetzes_ (BGBl. I Nr. 12/2020)]
besser vergleichbar zu machen.

Diese Seite ist rechtlich unverbindlich.
Fehler vorbehalten.
====

== COVID-19-Maßnahmengesetz

[NOTE]
====
Ausgegeben am 15. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/I/2020/12[BGBl. I Nr. 12/2020]) +
Gültig ab  16. März 2020 +
Gültig bis 21. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/I/2020/16[BGBl. I Nr. 16/2020])
====

*Betreten von Betriebsstätten zum Zweck des Erwerbs von Waren- und Dienstleistungen*

*§ 1.*
Beim Auftreten von COVID-19 kann der Bundesminister für Soziales, Gesundheit, Pflege und Konsumentenschutz durch Verordnung
das Betreten von Betriebsstätten oder nur bestimmten Betriebsstätten zum Zweck des Erwerbs von Waren und Dienstleistungen untersagen,
soweit dies zur Verhinderung der Verbreitung von COVID-19 erforderlich ist.
In der Verordnung kann geregelt werden, in welcher Zahl und zu welcher Zeit jene Betriebsstätten betreten werden dürfen, die vom Betretungsverbot ausgenommen sind.

*Betreten von bestimmten Orten*

*§ 2.*
Beim Auftreten von COVID-19 kann durch Verordnung das Betreten von bestimmten Orten untersagt werden,
soweit dies zur Verhinderung der Verbreitung von COVID-19 erforderlich ist. Die Verordnung ist

1. vom Bundesminister für Soziales, Gesundheit, Pflege und Konsumentenschutz zu erlassen, wenn sich ihre Anwendung auf das gesamte Bundesgebiet erstreckt,
2. vom Landeshauptmann zu erlassen, wenn sich ihre Anwendung auf das gesamte Landesgebiet erstreckt, oder
3. von der Bezirksverwaltungsbehörde zu erlassen, wenn sich ihre Anwendung auf den politischen Bezirk oder Teile desselben erstreckt.

Das Betretungsverbot kann sich auf bestimmte Zeiten beschränken.

*Mitwirkung von Organen des öffentlichen Sicherheitsdienstes*

*§ 2a.*
(1) Die Organe des öffentlichen Sicherheitsdienstes haben die nach diesem Bundesgesetz zuständigen Behörden und Organe
über deren Ersuchen bei der Ausübung ihrer beschriebenen Aufgaben bzw. zur Durchsetzung der vorgesehenen Maßnahmen
erforderlichenfalls unter Anwendung von Zwangsmitteln zu unterstützen.

(2) Sofern nach der fachlichen Beurteilung der nach diesem Bundesgesetz zuständigen Behörden im Rahmen der nach Abs. 1 vorgesehenen Unterstützung
für die Organe des öffentlichen Sicherheitsdienstes nach der Art der übertragbaren Krankheit und deren Übertragungsmöglichkeiten eine Gefährdung verbunden ist,
der nur durch besondere Schutzmaßnahmen begegnet werden kann, so sind die nach diesem Bundesgesetz zuständigen Behörden verpflichtet,
adäquate Schutzmaßnahmen zu treffen.

*Strafbestimmungen*

*§ 3.*
(1) Wer eine Betriebsstätte betritt, deren Betreten gemäß § 1 untersagt ist,
begeht eine Verwaltungsübertretung und ist mit einer Geldstrafe von bis zu 3 600 Euro zu bestrafen.

(2) Wer als Inhaber einer Betriebsstätte nicht dafür Sorge trägt, dass die Betriebsstätte, deren Betreten gemäß § 1 untersagt ist, nicht betreten wird,
begeht eine Verwaltungsübertretung und ist mit einer Geldstrafe von bis zu 30 000 Euro zu bestrafen. Wer als Inhaber einer Betriebsstätte nicht dafür Sorge trägt, dass die Betriebsstätte höchstens von der in der Verordnung genannten Zahl an Personen betreten wird, begeht eine Verwaltungsübertretung und ist mit einer Geldstrafe von bis zu 3 600 Euro zu bestrafen.

(3) Wer einen Ort betritt, dessen Betreten gemäß § 2 untersagt ist,
begeht eine Verwaltungsübertretung und ist mit einer Geldstrafe von bis zu 3 600 Euro zu bestrafen.

*Inkrafttreten*

*§ 4.*
(1) Dieses Bundesgesetz tritt mit Ablauf des Tages der Kundmachung in Kraft und mit Ablauf des 31. Dezember 2020 außer Kraft.

(2) Hat der Bundesminister gemäß § 1 eine Verordnung erlassen, gelangen die Bestimmungen des Epidemiegesetzes 1950, BGBl. Nr. 186/1950,
betreffend die Schließung von Betriebsstätten nicht zur Anwendung.

(3) Die Bestimmungen des Epidemiegesetzes 1950 bleiben unberührt.

(4) Verordnungen auf Grund dieses Bundesgesetzes können vor seinem Inkrafttreten erlassen werden, dürfen jedoch nicht vor diesem in Kraft treten.

*Vollziehung*

*§ 5.*
Mit der Vollziehung dieses Bundesgesetzes ist der Bundesminister für Soziales, Gesundheit, Pflege und Konsumentenschutz betraut.
