= BGBl. II Nr. 98/2020
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[CAUTION]
.Haftungsausschluss
====
Diese Seite dient nur dem Zweck, die verschiedenen Novellen der
https://www.ris.bka.gv.at/eli/bgbl/II/2020/98[_Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes_]
besser vergleichbar zu machen.

Diese Seite ist rechtlich unverbindlich.
Fehler vorbehalten.
====

== Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes

[NOTE]
====
Ausgegeben am 15. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/98[BGBl. II Nr. 98/2020]) +
Gültig ab  16. März 2020 +
Gültig bis 19. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/107[BGBl. II Nr. 107/2020])
====

*98. Verordnung des Bundesministers für Soziales, Gesundheit, Pflege und Konsumentenschutz gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes*

Auf Grund von § 2 Z 1 des COVID-19-Maßnahmengesetzes, https://www.ris.bka.gv.at/eli/bgbl/I/2020/12[BGBl. I Nr. 12/2020], wird verordnet:

*§ 1.*
Zur Verhinderung der Verbreitung von COVID-19 ist das Betreten öffentlicher Orte verboten.

*§ 2.*
Ausgenommen vom Verbot gemäß § 1 sind Betretungen,

1. die zur Abwendung einer unmittelbaren Gefahr für Leib, Leben und Eigentum erforderlich sind;
2. die zur Betreuung und Hilfeleistung von unterstützungsbedürftigen Personen dienen;
3. die zur Deckung der notwendigen Grundbedürfnisse des täglichen Lebens erforderlich sind und sichergestellt ist,
   dass am Ort der Deckung des Bedarfs zwischen den Personen ein Abstand von mindestens einem Meter eingehalten werden kann;
4. die für berufliche Zwecke erforderlich sind und sichergestellt ist,
   dass am Ort der beruflichen Tätigkeit zwischen den Personen ein Abstand von mindestens einem Meter eingehalten werden kann;
5. wenn öffentliche Orte im Freien alleine, mit Personen, die im gemeinsamen Haushalt leben,
   oder mit Haustieren betreten werden sollen,
   gegenüber anderen Personen ist dabei ein Abstand von mindestens einem Meter einzuhalten.

*§ 3.*
Die Benützung von Massenbeförderungsmitteln ist nur für Betretungen gemäß § 2 Z 1 bis 4 zulässig,
wobei bei der Benützung ein Abstand von mindestens einem Meter gegenüber anderen Personen einzuhalten ist.

*§ 4.*
Im Fall der Kontrolle durch Organe des öffentlichen Sicherheitsdienstes sind die Gründe,
warum eine Betretung gemäß § 2 zulässig ist, glaubhaft zu machen.

*§ 5.*
Diese Verordnung tritt mit 16. März 2020 in Kraft und mit Ablauf des 22. März 2020 außer Kraft.

*Anschober*
