= BGBl. II Nr. 98/2020
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[CAUTION]
.Haftungsausschluss
====
Diese Seite dient nur dem Zweck, die verschiedenen Novellen der
https://www.ris.bka.gv.at/eli/bgbl/II/2020/98[_Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes_]
besser vergleichbar zu machen.

Diese Seite ist rechtlich unverbindlich.
Fehler vorbehalten.
====

== Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes

[NOTE]
====
Ausgegeben am 15. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/98[BGBl. II Nr. 98/2020]) +
Novelle ausgegeben am 9. April 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/148[BGBl. II Nr. 148/2020]) +
Gültig ab  14. April 2020 +
Gültig bis 30. April 2020
====

*98. Verordnung des Bundesministers für Soziales, Gesundheit, Pflege und Konsumentenschutz gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes*

Auf Grund von § 2 Z 1 des COVID-19-Maßnahmengesetzes, https://www.ris.bka.gv.at/eli/bgbl/I/2020/12[BGBl. I Nr. 12/2020], wird verordnet:

*§ 1.*
Zur Verhinderung der Verbreitung von COVID-19 ist das Betreten öffentlicher Orte verboten.

*§ 2.*
Ausgenommen vom Verbot gemäß § 1 sind Betretungen,

1. die zur Abwendung einer unmittelbaren Gefahr für Leib, Leben und Eigentum erforderlich sind;
2. die zur Betreuung und Hilfeleistung von unterstützungsbedürftigen Personen dienen;
3. die zur Deckung der notwendigen Grundbedürfnisse des täglichen Lebens erforderlich sind und sichergestellt ist,
   dass am Ort der Deckung des Bedarfs zwischen den Personen ein Abstand von mindestens einem Meter eingehalten werden kann,
   sofern nicht durch entsprechende Schutzmaßnahmen das Infektionsrisiko minimiert werden kann.
   Diese Ausnahme schließt auch Eheschließungen und Begräbnisse im engen familiären Kreis mit ein;

 a. 3a. zum Erwerb von Waren oder Inanspruchnahme von Dienstleistungen nach Maßgabe der Verordnung des Bundesministers für Soziales, Gesundheit, Pflege und Konsumentenschutz
    betreffend vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19, BGBl. II Nr. 96/2020 idgF;

4. die für berufliche Zwecke erforderlich sind und sichergestellt ist,
   dass am Ort der beruflichen Tätigkeit zwischen den Personen ein Abstand von mindestens einem Meter eingehalten werden kann,
   sofern nicht durch entsprechende Schutzmaßnahmen das Infektionsrisiko minimiert werden kann.
   Das verpflichtende Tragen von den Mund- und Nasenbereich gut abdeckenden mechanischen Schutzvorrichtung als Barriere gegen Tröpfcheninfektion in Bereichen,
   wo dies nicht ohnehin auf Grund anderer Rechtsvorschriften verpflichtend erforderlich ist, ist nur im Einvernehmen zwischen Arbeitgeber und Arbeitnehmer zulässig.
   Dabei ist darauf zu achten, dass eine berufliche Tätigkeit vorzugweise außerhalb der Arbeitsstätte erfolgen soll,
   sofern dies möglich ist und Arbeitgeber und Arbeitnehmer darüber ein Einvernehmen finden.
5. wenn öffentliche Orte im Freien alleine, mit Personen, die im gemeinsamen Haushalt leben,
   oder mit Haustieren betreten werden sollen,
   gegenüber anderen Personen ist dabei ein Abstand von mindestens einem Meter einzuhalten.

*§ 3.*
Das Betreten von

1. Kuranstalten gemäß § 42a KAKuG ist für Kurgäste verboten,
2. Einrichtungen, die der Rehabilitation dienen, ist für Patienten/-innen verboten,
   ausgenommen zur Inanspruchnahme unbedingt notwendiger medizinischer Maßnahmen der Rehabilitation im Anschluss an die medizinische Akutbehandlung
   sowie im Rahmen von Unterstützungsleistungen für Allgemeine Krankenanstalten.

*§ 4.*
(1) Das Betreten des Kundenbereichs in Massenbeförderungsmitteln ist nur zulässig, wenn dabei eine den Mund- und Nasenbereich
gut abdeckende mechanische Schutzvorrichtung als Barriere gegen Tröpfcheninfektion getragen wird und bei der Benützung gegenüber Personen,
die nicht im gemeinsamen Haushalt leben, ein Abstand von mindestens einem Meter gegenüber anderen Personen eingehalten wird.
Die Pflicht zum Tragen der mechanischen Schutzvorrichtung gilt nicht für Kinder bis zum vollendeten sechsten Lebensjahr.

(2) Fahrgemeinschaften mit Personen, die nicht im gemeinsamen Haushalt leben, sind nur zulässig, wenn dabei eine den Mund- und Nasenbereich
gut abdeckende mechanische Schutzvorrichtung als Barriere gegen Tröpfcheninfektion getragen wird und gegenüber anderen Personen ein Abstand von mindestens einem Meter eingehalten wird.
Die Pflicht zum Tragen der mechanischen Schutzvorrichtung gilt nicht für Kinder bis zum vollendeten sechsten Lebensjahr.

*§ 5.*
Das Betreten von Sportplätzen ist verboten.

*§ 6.*
Im Fall der Kontrolle durch Organe des öffentlichen Sicherheitsdienstes sind die Gründe,
warum eine Betretung gemäß § 2 zulässig ist, glaubhaft zu machen.

*§ 7.*
(1) Diese Verordnung tritt mit 16. März 2020 in Kraft und mit Ablauf des 30. April 2020 außer Kraft.

(2) Die Änderungen durch die Novelle https://www.ris.bka.gv.at/eli/bgbl/II/2020/107[BGBl. II Nr. 107/2020] treten mit dem der Kundmachung folgenden Tag in Kraft.

(3) Die Änderungen dieser Verordnung durch die Verordnung BGBl. II Nr. 148/2020 treten mit Ablauf des 13. April 2020 in Kraft.

*Anschober*
