= BGBl. II Nr. 96/2020
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[CAUTION]
.Haftungsausschluss
====
Diese Seite dient nur dem Zweck, die verschiedenen Novellen der
https://www.ris.bka.gv.at/eli/bgbl/II/2020/96[_Vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19_ (BGBl. II Nr. 96/2020)]
besser vergleichbar zu machen.

Diese Seite ist rechtlich unverbindlich.
Fehler vorbehalten.
====

== Vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19

[NOTE]
====
Ausgegeben am 15. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/96[BGBl. II Nr. 96/2020]) +
Novelle ausgegeben am 20. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/110[BGBl. II Nr. 110/2020]) +
Gültig ab 21. März 2020 +
Gültig bis 22. März 2020 (https://www.ris.bka.gv.at/eli/bgbl/II/2020/112[BGBl. II Nr. 112/2020])
====

*96. Verordnung des Bundesministers für Soziales, Gesundheit, Pflege und Konsumentenschutz betreffend vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19*

Auf Grund § 1 des Bundesgesetzes betreffend vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19 (COVID-19 Maßnahmengesetz), BGBl. I Nr. 12/2020 wird verordnet:

*§ 1.*
Das Betreten des Kundenbereichs von Betriebsstätten des Handels und von Dienstleistungsunternehmen sowie von Freizeit- und Sportbetrieben
zum Zweck des Erwerbs von Waren oder der Inanspruchnahme von Dienstleistungen oder der Benützung von Freizeit- und Sportbetrieben ist untersagt.

*§ 2.*
(1) § 1 gilt nicht für folgende Bereiche:

1. öffentliche Apotheken
2. Lebensmittelhandel (einschließlich Verkaufsstellen von Lebensmittelproduzenten) und bäuerlichen Direktvermarktern
3. .Drogerien und Drogeriemärkte
4. Verkauf von Medizinprodukten und Sanitärartikeln, Heilbehelfen und Hilfsmitteln
5. Gesundheits- und Pflegedienstleistungen
6. Dienstleistungen für Menschen mit Behinderungen die von den Ländern im Rahmen der Behindertenhilfe–, Sozialhilfe–, Teilhabe– bzw. Chancengleichheitsgesetze erbracht werden
7. veterinärmedizinische Dienstleistungen
8. Verkauf von Tierfutter
9. Verkauf und Wartung von Sicherheits- und Notfallprodukten
10. Notfall-Dienstleistungen
11. Agrarhandel einschließlich Schlachttierversteigerungen sowie der Gartenbaubetrieb und der Landesproduktenhandel mit Saatgut, Futter und Düngemittel
12. Tankstellen
13. Banken
14. Postdiensteanbieter einschließlich deren Postpartner, soweit diese Postpartner unter die Ausnahmen des § 2 fallen
    sowie Postgeschäftsstellen iSd § 3 Z 7 PMG, welche von einer Gemeinde betrieben werden oder in Gemeinden liegen,
    in denen die Versorgung durch keine andere unter § 2 fallende Postgeschäftsstelle erfolgen kann,
    jedoch ausschließlich für die Erbringung von Postdienstleistungen und die unter § 2 erlaubten Tätigkeiten, und Telekommunikation.
15. Dienstleistungen im Zusammenhang mit der Rechtspflege
16. Lieferdienste
17. Öffentlicher Verkehr
18. Tabakfachgeschäfte und Zeitungskioske
19. Hygiene und Reinigungsdienstleistungen
20. Abfallentsorgungsbetriebe
21. KFZ-Werkstätten.

(2) Die Ausnahmen nach Abs. 1 Z 3, 4, 8, 9 und 11 gelten an Werktagen von 07.40 Uhr bis längstens 19.00 Uhr.
Restriktivere Öffnungszeitenregeln aufgrund anderer Rechtsvorschriften bleiben unberührt.

(3) Die Ausnahmen nach Abs. 1 Z 2 gilt an Werktagen von 07.40 Uhr bis längstens 19.00 Uhr, sofern es sich nicht um eine Verkaufsstelle von Lebensmittelproduzenten handelt.
Restriktivere Öffnungszeitenregeln aufgrund anderer Rechtsvorschriften bleiben unberührt.

*§ 3.*
(1) Das Betreten von Betriebsstätten sämtlicher Betriebsarten der Gastgewerbe ist untersagt.

(2) Abs. 1 gilt nicht für Gastgewerbetriebe, welche innerhalb folgender Einrichtungen betrieben werden:

1. Kranken-und Kuranstalten;
2. Pflegeanstalten und Seniorenheime;
3. Einrichtungen zur Betreuung und Unterbringung von Kindern und Jugendlichen einschließlich Schulen und Kindergärten;
4. Betrieben, wenn diese ausschließlich durch Betriebsangehörige genützt werden dürfen.

(3) Abs. 1 gilt nicht für Beherbergungsbetriebe, wenn in der Betriebsstätte Speisen und Getränke ausschließlich an Beherbergungsgäste verabreicht und ausgeschenkt werden.

(4) Abs. 1 gilt nicht für Campingplätze und öffentlichen Verkehrsmitteln, wenn dort Speisen und Getränke
ausschließlich an Gäste des Campingplatzes bzw. öffentlicher Verkehrsmitteln verabreicht und ausgeschenkt werden.

(5) Abs. 1 gilt nicht für Lieferservice.

*§ 4.*
(1) Diese Verordnung tritt mit Ablauf des 13. April 2020 außer Kraft.

(2) Die Änderungen dieser Verordnung durch die Verordnung BGBl. II Nr. 112/2020 treten mit dem der Kundmachung folgenden Tag in Kraft.

*Anschober*
