= Covid-19-Maßnahmengesetz
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:repo: https://github.com/MarkusMit/Covid19Massnahmengesetz

Novellen des Covid-19-Maßnahmengesetzes und darauf basierender Verordnungen

[CAUTION]
.Haftungsausschluss
====
Diese Seite dient nur dem Zweck, die verschiedenen Novellen des
https://www.ris.bka.gv.at/eli/bgbl/I/2020/12["COVID-19 Gesetz" (BGBl. I Nr. 12/2020)]
und der darauf basierenden Verordnungen +
https://www.ris.bka.gv.at/eli/bgbl/II/2020/96["Vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19" (BGBl. II Nr. 96/2020)],
sowie +
https://www.ris.bka.gv.at/eli/bgbl/II/2020/98["Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes" (BGBl. II Nr. 98/2020)] +
besser vergleichbar zu machen.

Diese Seite ist rechtlich unverbindlich.
Fehler vorbehalten. +
Rechlich verbindliche Informationen  im https://www.ris.bka.gv.at/[Rechtsinformationssystem des Bundes (ris.bka.gv.at)].
====

== Covid-19-Maßnahmengesetz

https://www.ris.bka.gv.at/eli/bgbl/I/2020/12[BGBl. I Nr. 12/2020 (RIS)] COVID-19-Maßnahmengesetz

* link:{repo}/blob/bgbl_i_12-2020/BGBL_I_12-2020.adoc[ursprüngliche Fassung]

(TODO Vergleichslinks der Novellen)

=== Verordnung "Vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19"

https://www.ris.bka.gv.at/eli/bgbl/II/2020/96[BGBl. II Nr. 96/2020 (RIS)] Vorläufige Maßnahmen zur Verhinderung der Verbreitung von COVID-19

* link:{repo}/blob/bgbl_ii_96-2020/BGBL_II_96-2020.adoc[ursprüngliche Fassung]

* link:{repo}/blob/bgbl_ii_110-2020/BGBL_II_96-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 110/2020], g.a. 20. März 2020
** Vergleich mit: link:{repo}/commit/831453ff4fd14adeaedb4c88ca79a7a7cde019c3?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[ursprünglicher Fassung]
(link:{repo}/commit/831453ff4fd14adeaedb4c88ca79a7a7cde019c3#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])

* link:{repo}/blob/bgbl_ii_112-2020/BGBL_II_96-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 112/2020], g.a. 23. März 2020
** Vergleich mit: link:{repo}/compare/bgbl_ii_96-2020%2E%2E%2Ebgbl_ii_112-2020?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[ursprünglicher Fassung]
(link:{repo}/compare/bgbl_ii_96-2020%2E%2E%2Ebgbl_ii_112-2020#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])
/ link:{repo}/compare/bgbl_ii_110-2020%2E%2E%2Ebgbl_ii_112-2020?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[vorheriger Fassung (107/2020)]
(link:{repo}/compare/bgbl_ii_110-2020%2E%2E%2Ebgbl_ii_112-2020#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])

* link:{repo}/blob/bgbl_ii_130-2020/BGBL_II_96-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 130/2020], g.a. 3. April 2020
** Vergleich mit: link:{repo}/compare/bgbl_ii_96-2020%2E%2E%2Ebgbl_ii_130-2020?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[ursprünglicher Fassung]
(link:{repo}/compare/bgbl_ii_96-2020%2E%2E%2Ebgbl_ii_130-2020#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])
/ link:{repo}/compare/bgbl_ii_112-2020%2E%2E%2Ebgbl_ii_130-2020?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[vorheriger Fassung (112/2020)]
(link:{repo}/compare/bgbl_ii_112-2020%2E%2E%2Ebgbl_ii_130-2020#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])

* link:{repo}/blob/bgbl_ii_151-2020/BGBL_II_96-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 151/2020], g.a. 14. April 2020
** Vergleich mit: link:{repo}/compare/bgbl_ii_96-2020%2E%2E%2Ebgbl_ii_151-2020?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[ursprünglicher Fassung]
(link:{repo}/compare/bgbl_ii_96-2020%2E%2E%2Ebgbl_ii_151-2020#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])
/ link:{repo}/compare/bgbl_ii_130-2020%2E%2E%2Ebgbl_ii_151-2020?short_path=9b4f899#diff-9b4f89980d188984cd304a404cf74659[vorheriger Fassung (130/2020)]
(link:{repo}/compare/bgbl_ii_130-2020%2E%2E%2Ebgbl_ii_151-2020#diff-9b4f89980d188984cd304a404cf74659[q, title=Quelltext])

=== Verordung "Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes"

https://www.ris.bka.gv.at/eli/bgbl/II/2020/98[BGBl. II Nr. 98/2020 (RIS)] Verordnung gemäß § 2 Z 1 des COVID-19-Maßnahmengesetzes

* link:{repo}/blob/bgbl_ii_98-2020/BGBL_II_98-2020.adoc[ursprüngliche Fassung]

* link:{repo}/blob/bgbl_ii_107-2020/BGBL_II_98-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 107/2020], g.a. 19. März 2020
** Vergleich mit: link:{repo}/commit/c17b8d56fdea9f6887151c2f30fd33d8c1b46e75?short_path=4e67f25#diff-4e67f2502398b67e76f7fab2e408ace1[ursprünglicher Fassung]
   (link:{repo}/commit/c17b8d56fdea9f6887151c2f30fd33d8c1b46e75#diff-4e67f2502398b67e76f7fab2e408ace1[q, title=Quelltext])

* link:{repo}/blob/bgbl_ii_108-2020/BGBL_II_98-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 108/2020], g.a. 20. März 2020
** Vergleich mit: link:{repo}/compare/d143fdec668108db2298fea9ecd83cd9732f2db0..3947d4aa4698a6f03cec5ca974b74efdd9a56493?short_path=4e67f25#diff-4e67f2502398b67e76f7fab2e408ace1[ursprünglicher Fassung]
(link:{repo}/compare/d143fdec668108db2298fea9ecd83cd9732f2db0..3947d4aa4698a6f03cec5ca974b74efdd9a56493#diff-4e67f2502398b67e76f7fab2e408ace1[q, title=Quelltext])
/ link:{repo}/commit/3947d4aa4698a6f03cec5ca974b74efdd9a56493?short_path=4e67f25#diff-4e67f2502398b67e76f7fab2e408ace1[vorheriger Fassung (107/2020)]
(link:{repo}/commit/3947d4aa4698a6f03cec5ca974b74efdd9a56493#diff-4e67f2502398b67e76f7fab2e408ace1[q, title=Quelltext])

* link:{repo}/blob/bgbl_ii_148-2020/BGBL_II_98-2020.adoc[konsolidierte Fassung, Novelle BGBl. II 148/2020], g.a. 14. April 2020
** Vergleich mit: link:{repo}/compare/bgbl_ii_98-2020%2E%2E%2Ebgbl_ii_148-2020?short_path=4e67f25#diff-4e67f2502398b67e76f7fab2e408ace1[ursprünglicher Fassung]
(link:{repo}/compare/bgbl_ii_98-2020%2E%2E%2Ebgbl_ii_148-2020#diff-4e67f2502398b67e76f7fab2e408ace1[q, title=Quelltext])
/ link:{repo}/compare/bgbl_ii_108-2020%2E%2E%2Ebgbl_ii_148-2020?short_path=4e67f25#diff-4e67f2502398b67e76f7fab2e408ace1[vorheriger Fassung (108/2020)]
(link:{repo}/compare/bgbl_ii_108-2020%2E%2E%2Ebgbl_ii_148-2020#diff-4e67f2502398b67e76f7fab2e408ace1[q, title=Quelltext])
